/* ════════════════════════════════════════════════════════════
   CodeSera — scripts/build-assets.js
   Regenerates assets.js from lesson/ source files.
   Run: node scripts/build-assets.js  OR  npm run build
════════════════════════════════════════════════════════════ */
const fs   = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');

// In new structure: lesson files are in lesson/
// Fallback to root for backwards compat
function readFile(name) {
  const lessonPath = path.join(root, 'lesson', name);
  const rootPath   = path.join(root, name);
  if (fs.existsSync(lessonPath)) return fs.readFileSync(lessonPath, 'utf8');
  return fs.readFileSync(rootPath, 'utf8');
}

function esc(s) {
  return s.replace(/\\/g,'\\\\').replace(/`/g,'\\`').replace(/\$\{/g,'\\${');
}

const css  = readFile('lesson.css');
const lcss = readFile('lesson-light.css');
const js   = readFile('lesson.js');
const chat = readFile('lesson-chat.js');

const out =
  `/* AUTO-GENERATED by scripts/build-assets.js — do not edit directly */\n` +
  `const LESSON_CSS = \`${esc(css)}\`;\n\n` +
  `const LESSON_LIGHT_CSS = \`${esc(lcss)}\`;\n\n` +
  `const LESSON_JS = \`${esc(js)}\`;\n\n` +
  `const LESSON_CHAT_JS = \`${esc(chat)}\`;\n`;

// Output to src/assets.js in new structure, fallback to root
const outPath = fs.existsSync(path.join(root, 'src'))
  ? path.join(root, 'src', 'assets.js')
  : path.join(root, 'assets.js');

fs.writeFileSync(outPath, out, 'utf8');
console.log(`✅ assets.js rebuilt — ${(out.length/1024).toFixed(1)} KB → ${path.relative(root, outPath)}`);
